# Generated by Django 4.1 on 2022-08-26 04:35

from django.db import migrations


class Migration(migrations.Migration):
    """
    placeholder description
    """

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
