# Generated by Django 4.1 on 2022-09-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_colln'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.FileField(max_length=30, upload_to=''),
        ),
    ]
