name: Backend Testing 
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up env variables
      run: |
        touch .env
        echo MONGO_DB_USERNAME=pablol >> .env
        echo MONGO_DB_PASSWORD=zhOEdo3dNhScqTEA >> .env
        echo MONGO_DB_HOST=cluster0.n3en270.mongodb.net >> .env

